# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
